from pathlib import Path

ROOT_FOLDER = Path(__file__).parent
FILES_FOLDER = ROOT_FOLDER / 'files'
WINDOW_ICON_PATH = FILES_FOLDER / 'icon.svg'

# Sizing
BIG_FONT_SIZE = 40
MEDIUM_FONT_SIZE = 28
SMALL_FONT_SIZE = 18
TEXT_MARGIN = 15
MINIMUM_WIDTH = 500
