from pathlib import Path

ROOT_FOLDER = Path(__file__).parent
FILES_FOLDER = ROOT_FOLDER / 'files'
WINDOW_ICON_PATH = FILES_FOLDER / 'icon.ico'

# Colors
PRIMARY_COLOR = '#BB9311'
DARKER_PRIMARY_COLOR = '#A27F0E'
DARKEST_PRIMARY_COLOR = '#97760C'
# PRIMARY_COLOR = '#1e81b0'
# DARKER_PRIMARY_COLOR = '#16658a'
# DARKEST_PRIMARY_COLOR = '#115270'

# Sizing
BIG_FONT_SIZE = 40
MEDIUM_FONT_SIZE = 24
SMALL_FONT_SIZE = 18
TEXT_MARGIN = 15
MINIMUM_WIDTH = 450
